CREATE TABLE FUTBOLISTA(
CEDULA VARCHAR(50),
NOMBRES VARCHAR(50),
APELLIDOS VARCHAR(50),
FECHA_NACIMIENTO DATETIME,
PAIS VARCHAR(50),
DIRECCION VARCHAR(50),
DESCRIPCION VARCHAR(50)
)

CREATE TABLE EQUIPOS(
NOMBRE_EQUIPO VARCHAR(50),
DESCRIPCION VARCHAR(50),
NUMERO_JUGADORES INTEGER,
PAIS VARCHAR(50),
FALTAS INTEGER,
CIUDAD VARCHAR(50),
ESTADIO VARCHAR(50)
)

CREATE TABLE HISTORICO_EQUIPOS(
NOMBRE_EQUIPO VARCHAR(50),
NUMERO_JUGADORES INTEGER,
FECHA_INICIO DATETIME,
FECHA_FIN DATETIME
)
